

bird_direction = 0; %Degrees clockwise from north.
bird_speed = 10; %m/s
wind_direction = 10; %Degrees clockwise from north.
wind_speed = 15; %m/s
axial_induction = 0;

[ angle_of_orientation_degrees ...
  bird_downwind_relative_direction_radians ...
  Vbx ...
  Vby ...
  Vx ] = BirdOrientation(bird_direction, ...
                         bird_speed, ...
                         wind_direction, ...
                         wind_speed, ...
                         axial_induction)
                     
   
i = 0;
wind_speeds = [1:0.1:15];
for wind_speed = wind_speeds
    i = i+1;
    [ angle_of_orientation_degrees ...
      bird_downwind_relative_direction_radians ...
      Vbx ...
      Vby ...
      Vx ] = BirdOrientation(bird_direction, ...
                             bird_speed, ...
                             wind_direction, ...
                             wind_speed, ...
                             axial_induction);
                         
     bird_orientations(i) = angle_of_orientation_degrees;
end

figure;
plot(wind_speeds,bird_orientations);
xlabel('bird_orientations');