load('WindFarmProbabilityData');

mean_bird_height = 80;
variance_bird_height = 20;
radar_range = 500;
bird_frequency = 1;
avoidance_rate = 0.95;

collision_rate = CalculateCollisionRate(windfarm_probabilities, ...
                                        x_ticks, ...
                                        y_ticks, ...
                                        mean_bird_height, ...
                                        variance_bird_height, ...
                                        radar_range, ...
                                        bird_frequency, ...
                                        avoidance_rate)